// Promise.resolve(1).then(res => {
//     console.log(1);
// }).then(res => {
//     console.log(2);
// }).then(res => {
//     console.log(3);
// }, err => new Error('ddd')).then(res => {
//     console.log(4);
// }).then(res => {
//     console.log(5);
// }).catch(err => {
//     console.log(err)
// })
